version: '3'
services:
  redis:
    image: redis:alpine
  mongodb:
    image: mongo
  service:
    build: .
    command: go run main.go
    environment:
      - APP=/go/src/github.com/klebervirgilio/simple-healthchecker-go
      - WEB_SERVER_PORT=:4040
      - MONGO_HOST=mongodb:27017
      - MONGO_TIMEOUT=3
      - REDIS_HOST=redis:6379
      - REDIS_TIMEOUT=3
      - WAIT=2
    working_dir: /go/src/github.com/klebervirgilio/simple-healthchecker-go
    volumes:
      - .:/go/src/github.com/klebervirgilio/simple-healthchecker-go
    ports:
      - 4040:4040
